"""K8 Self-Creation Engine — detect capability gaps, spawn agents/skills.

The genesis engine reads the soul (goals, environment, gaps) and generates
agents/skills/professions as SKILL.md drafts. Nothing activates without
player approval (Invariant 10).
"""
from __future__ import annotations

import json
from pathlib import Path

from .common import (
    now_iso,
    read_text,
    shell_path,
    stable_suffix,
    today,
    write_text,
)
from .professions import profession_gaps


def detect_gaps(root: Path) -> list[dict]:
    """Detect capability gaps: VSM professions without holders + domain needs."""
    gaps = profession_gaps(root)
    domain_gaps = _detect_domain_gaps(root)
    return gaps + domain_gaps


def spawn_draft(root: Path, gap: dict) -> Path:
    """Generate a draft SKILL.md for a capability gap. Draft only — needs approval."""
    profession = gap.get("profession", "unknown")
    display = gap.get("display", profession)
    model_tier = gap.get("model_tier", "mid")
    vsm = gap.get("vsm", "S1")

    draft_id = f"draft_agent_{profession}_{today().replace('-', '')}_{stable_suffix(profession + now_iso(), 6)}"
    draft_dir = root / "inbox" / f"{draft_id}"
    draft_dir.mkdir(parents=True, exist_ok=True)

    skill_md = f"""---
name: agent.{profession}
description: Auto-generated agent for {display} ({vsm})
vsm: {vsm}
profession: {profession}
model_tier: {model_tier}
reads: {json.dumps(gap.get('reads', []))}
writes: {json.dumps(gap.get('writes', []))}
trigger: {{kind: invoke}}
sunset: {{unused_after_months: 6}}
genesis: {{template: {profession}, domain: generic}}
status: draft
created: {today()}
---

# {display} Agent

Auto-generated by genesis engine to fill {profession} gap.

## Capabilities

TODO(player): review and approve before activation.

## Triggers

- {', '.join(gap.get('triggers', ['on_demand']))}
"""
    write_text(draft_dir / "SKILL.md", skill_md)

    manifest = {
        "draft_id": draft_id,
        "gap": gap,
        "created": now_iso(),
        "status": "draft",
        "requires": "player_approval",
    }
    write_text(draft_dir / "manifest.json", json.dumps(manifest, ensure_ascii=False, indent=2))
    return draft_dir


def validate_draft(root: Path, draft_id: str) -> dict:
    """Validate a genesis draft against laws and existing modules."""
    draft_dir = _find_draft(root, draft_id)
    skill_path = draft_dir / "SKILL.md"
    if not skill_path.exists():
        return {"valid": False, "errors": ["missing SKILL.md"]}

    text = read_text(skill_path)
    errors = []

    if "reads:" not in text:
        errors.append("missing reads declaration")
    if "writes:" not in text:
        errors.append("missing writes declaration")
    if "vsm:" not in text:
        errors.append("missing VSM assignment")

    from .common import parse_frontmatter
    fm = parse_frontmatter(text)
    writes = fm.get("writes", [])
    if isinstance(writes, list) and "events" in writes:
        if fm.get("vsm") in ("S1",):
            pass
        elif fm.get("profession") not in ("distiller", "operator"):
            errors.append("only distiller/operator should write events directly")

    existing = _list_registered_modules(root)
    name = fm.get("name", "")
    if name in existing:
        errors.append(f"module '{name}' already registered — consider reusing")

    return {"valid": len(errors) == 0, "errors": errors, "draft_id": draft_id}


def register_module(root: Path, draft_id: str) -> Path:
    """Register an approved draft into shell/modules/."""
    validation = validate_draft(root, draft_id)
    if not validation["valid"]:
        raise ValueError(f"draft failed validation: {validation['errors']}")

    draft_dir = _find_draft(root, draft_id)
    module_dir = shell_path(root) / "modules" / draft_id.replace("draft_", "")
    module_dir.mkdir(parents=True, exist_ok=True)

    import shutil
    for f in draft_dir.iterdir():
        shutil.copy2(f, module_dir / f.name)

    _update_registry(root, draft_id, module_dir)

    manifest_path = module_dir / "manifest.json"
    if manifest_path.exists():
        manifest = json.loads(read_text(manifest_path))
        manifest["status"] = "registered"
        manifest["registered_at"] = now_iso()
        write_text(manifest_path, json.dumps(manifest, ensure_ascii=False, indent=2))

    return module_dir


def sunset_module(root: Path, module_name: str) -> None:
    """Deactivate an unused module."""
    registry_path = shell_path(root) / "modules" / "_registry.md"
    if not registry_path.exists():
        return
    text = read_text(registry_path)
    text = text.replace(
        f"- {module_name}:",
        f"- ~~{module_name}~~ (sunset {today()}):",
    )
    write_text(registry_path, text)


# --- Internal ---

def _detect_domain_gaps(root: Path) -> list[dict]:
    """Detect domain-specific capability gaps from soul genesis environment."""
    try:
        from .soul import read_genesis
        genesis = read_genesis(root)
    except FileNotFoundError:
        return []

    gaps = []
    from .common import parse_frontmatter
    genesis_path = root / "soul" / "_genesis.md"
    if genesis_path.exists():
        text = read_text(genesis_path)
        if "交易" in text or "量化" in text:
            gaps.append({"profession": "risk_officer", "display": "风控官", "vsm": "S3", "holder_type": "agent", "model_tier": "high", "domain": True})
        if "社群" in text or "community" in text.lower():
            gaps.append({"profession": "engagement_sentinel", "display": "活跃度哨兵", "vsm": "S2", "holder_type": "agent", "model_tier": "low", "domain": True})
        if "内容" in text or "content" in text.lower():
            gaps.append({"profession": "topic_oracle", "display": "选题预言家", "vsm": "S4", "holder_type": "agent", "model_tier": "high", "domain": True})
    return gaps


def _find_draft(root: Path, draft_id: str) -> Path:
    candidates = list((root / "inbox").glob(f"**/{draft_id}"))
    if len(candidates) == 1:
        return candidates[0]
    candidates = list((root / "inbox").glob(f"**/*{draft_id}*"))
    dirs = [c for c in candidates if c.is_dir()]
    if len(dirs) == 1:
        return dirs[0]
    raise FileNotFoundError(f"genesis draft not found: {draft_id}")


def _list_registered_modules(root: Path) -> set[str]:
    registry_path = shell_path(root) / "modules" / "_registry.md"
    if not registry_path.exists():
        return set()
    text = read_text(registry_path)
    return set(m.strip() for m in __import__("re").findall(r"^- ([\w.]+):", text, __import__("re").MULTILINE))


def _update_registry(root: Path, draft_id: str, module_dir: Path) -> None:
    registry_path = shell_path(root) / "modules" / "_registry.md"
    if not registry_path.exists():
        write_text(registry_path, f"---\ntype: module_registry\nupdated: {today()}\n---\n\n# Module Registry\n\n")
    text = read_text(registry_path)
    module_name = draft_id.replace("draft_", "")
    if module_name not in text:
        text = text.rstrip() + f"\n- {module_name}: registered {today()}, path: {module_dir}\n"
        write_text(registry_path, text)
